# Generated by Django 3.2.8 on 2022-06-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='poster_img',
            field=models.ImageField(null=True, upload_to='cakes/'),
        ),
    ]
