# Generated by Django 3.2.8 on 2022-07-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
