# Generated by Django 3.2.8 on 2022-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_cake_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='poster_img',
            field=models.ImageField(blank=True, null=True, upload_to='cakes/'),
        ),
    ]
