# Generated by Django 3.2.8 on 2022-07-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_cake_poster_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='poster_img',
            field=models.ImageField(blank=True, null=True, upload_to='cakes_selected/'),
        ),
    ]
