# Generated by Django 3.2.8 on 2021-10-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoption',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
