# Generated by Django 3.2.8 on 2021-10-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211018_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
