# Generated by Django 3.2.8 on 2021-10-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_review_rating'),
        ('orders', '0008_auto_20211024_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunit',
            name='cake',
        ),
        migrations.AddField(
            model_name='orderunit',
            name='cake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_cake', to='catalog.cake'),
            preserve_default=False,
        ),
    ]
